Repository mattermost/mattermost-plugin-channel-export, pull requests merged in 2024-09, with the labels that each got.

#49 Permission and error messages improvements
  plugin.json
  server/api.go
  server/api_test.go
  server/command_hooks.go
  server/command_hooks_test.go
  server/manifest.go
  webapp/src/manifest.js
Labels: 2: Dev Review, 3: QA Review

#55 [GH-51] Added conditional to disallow export in archived channel when it is not visible to users
  server/api.go
  server/api_test.go
Labels: 4: Reviews Complete

#48 [MM-46]: Updated the message for exporting channels
  server/command_hooks.go
  server/command_hooks_test.go
Labels: 3: QA Review

#54 Update default permission for system admin
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 2: Dev Review, 3: QA Review

#56 tests: cover hasPermissionToExportChannel
  server/api_test.go
  server/command_hooks_test.go
Labels: 4: Reviews Complete
